//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepdreamGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepdreamGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete image ähnelt.
        /// </summary>
        public static string action_delete_image {
            get {
                return ResourceManager.GetString("action_delete_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected images ähnelt.
        /// </summary>
        public static string action_delete_selected_images {
            get {
                return ResourceManager.GetString("action_delete_selected_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string action_details {
            get {
                return ResourceManager.GetString("action_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open image ähnelt.
        /// </summary>
        public static string action_open_image {
            get {
                return ResourceManager.GetString("action_open_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open style image ähnelt.
        /// </summary>
        public static string action_open_style_image {
            get {
                return ResourceManager.GetString("action_open_style_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string action_process_cancel {
            get {
                return ResourceManager.GetString("action_process_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished ähnelt.
        /// </summary>
        public static string action_process_finished {
            get {
                return ResourceManager.GetString("action_process_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string action_process_start {
            get {
                return ResourceManager.GetString("action_process_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save image ähnelt.
        /// </summary>
        public static string action_save_image {
            get {
                return ResourceManager.GetString("action_save_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save selected images ähnelt.
        /// </summary>
        public static string action_save_selected_images {
            get {
                return ResourceManager.GetString("action_save_selected_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save report for selected images ähnelt.
        /// </summary>
        public static string action_save_selected_report {
            get {
                return ResourceManager.GetString("action_save_selected_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select none ähnelt.
        /// </summary>
        public static string action_selct_none {
            get {
                return ResourceManager.GetString("action_selct_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        /// </summary>
        public static string action_select_all {
            get {
                return ResourceManager.GetString("action_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial image ähnelt.
        /// </summary>
        public static string info_base_image {
            get {
                return ResourceManager.GetString("info_base_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking dependencies ähnelt.
        /// </summary>
        public static string info_checking_dependencies {
            get {
                return ResourceManager.GetString("info_checking_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string info_confirm_cancel {
            get {
                return ResourceManager.GetString("info_confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will cause loosing progress of the currently processed image. Fully processed images are not affected. ähnelt.
        /// </summary>
        public static string info_confirm_cancel_details {
            get {
                return ResourceManager.GetString("info_confirm_cancel_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string info_confirm_close {
            get {
                return ResourceManager.GetString("info_confirm_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved changes will be lost. ähnelt.
        /// </summary>
        public static string info_confirm_close_detail {
            get {
                return ResourceManager.GetString("info_confirm_close_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string info_confirm_delete {
            get {
                return ResourceManager.GetString("info_confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All detail-windows showing this image will be closed. Cannot be undone. ähnelt.
        /// </summary>
        public static string info_confirm_delete_detail {
            get {
                return ResourceManager.GetString("info_confirm_delete_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start processing? ähnelt.
        /// </summary>
        public static string info_confirm_start {
            get {
                return ResourceManager.GetString("info_confirm_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This might take a long time. Consider increasing memory size and assigned CPUs. ähnelt.
        /// </summary>
        public static string info_confirm_start_details {
            get {
                return ResourceManager.GetString("info_confirm_start_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot open file ähnelt.
        /// </summary>
        public static string info_could_not_open_file {
            get {
                return ResourceManager.GetString("info_could_not_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string info_details {
            get {
                return ResourceManager.GetString("info_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t find docker. Application will be terminated. Try to start Docker manually. ähnelt.
        /// </summary>
        public static string info_docker_not_installed {
            get {
                return ResourceManager.GetString("info_docker_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docker isn&apos;t running yet. Trying to start docker, this might take a while. ähnelt.
        /// </summary>
        public static string info_docker_starting {
            get {
                return ResourceManager.GetString("info_docker_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string info_error {
            get {
                return ResourceManager.GetString("info_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start Docker or the muelmx/neuralart_exec image is not installed correctly. Closing application. ähnelt.
        /// </summary>
        public static string info_error_docker_container {
            get {
                return ResourceManager.GetString("info_error_docker_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process was cancled. May there is not enough RAM reserved for docker. This can be changed in the docker settings. Alternatively you can lower the number of iterations or take a smaller picture. ähnelt.
        /// </summary>
        public static string info_error_ram {
            get {
                return ResourceManager.GetString("info_error_ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process was cancled. An undefined error occured. Maybe the resolution of your picture is too high or the reserved RAM is too low. Errorcode: ähnelt.
        /// </summary>
        public static string info_error_undefined {
            get {
                return ResourceManager.GetString("info_error_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process was cancled. Maybe the working folder wasn&apos;t aprroved to docker. You can change this in the docker settings. ähnelt.
        /// </summary>
        public static string info_error_workingdirectory {
            get {
                return ResourceManager.GetString("info_error_workingdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transparencies will be filled ähnelt.
        /// </summary>
        public static string info_fill_transparency {
            get {
                return ResourceManager.GetString("info_fill_transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected image might contain transparent areas that will be filled with black color. Continue? ähnelt.
        /// </summary>
        public static string info_fill_transparency_detail {
            get {
                return ResourceManager.GetString("info_fill_transparency_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preparing... ähnelt.
        /// </summary>
        public static string info_preparing {
            get {
                return ResourceManager.GetString("info_preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelling Process... ähnelt.
        /// </summary>
        public static string info_process_will_be_canceled {
            get {
                return ResourceManager.GetString("info_process_will_be_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t rotate. ähnelt.
        /// </summary>
        public static string info_rotation {
            get {
                return ResourceManager.GetString("info_rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In order to calculate the correct scaling value for rotation an image must be loaded. ähnelt.
        /// </summary>
        public static string info_rotation_detail {
            get {
                return ResourceManager.GetString("info_rotation_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change scaling. ähnelt.
        /// </summary>
        public static string info_scaling {
            get {
                return ResourceManager.GetString("info_scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In order to prevent black borders when rotating, the scaling value is changed to a new minimun automatically. This value depends on the rotation angle. ähnelt.
        /// </summary>
        public static string info_scaling_detail {
            get {
                return ResourceManager.GetString("info_scaling_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select image ähnelt.
        /// </summary>
        public static string info_select_image {
            get {
                return ResourceManager.GetString("info_select_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select style ähnelt.
        /// </summary>
        public static string info_select_style {
            get {
                return ResourceManager.GetString("info_select_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serialnumber ähnelt.
        /// </summary>
        public static string info_serial {
            get {
                return ResourceManager.GetString("info_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style image ähnelt.
        /// </summary>
        public static string info_style_image {
            get {
                return ResourceManager.GetString("info_style_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Time remaining:  ähnelt.
        /// </summary>
        public static string info_time_remainnig {
            get {
                return ResourceManager.GetString("info_time_remainnig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait... ähnelt.
        /// </summary>
        public static string info_wait {
            get {
                return ResourceManager.GetString("info_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achieved change ähnelt.
        /// </summary>
        public static string param_achieved_change {
            get {
                return ResourceManager.GetString("param_achieved_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 = Less, 10 = More ähnelt.
        /// </summary>
        public static string param_achieved_change_tooltip {
            get {
                return ResourceManager.GetString("param_achieved_change_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string param_comment {
            get {
                return ResourceManager.GetString("param_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string param_description {
            get {
                return ResourceManager.GetString("param_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger pattern ähnelt.
        /// </summary>
        public static string param_helpsample {
            get {
                return ResourceManager.GetString("param_helpsample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay for the base image. Rotation, size and transparency is adjustable. It might trigger the model to generate specific patterns (Animals etc.) ähnelt.
        /// </summary>
        public static string param_helpsample_tooltip {
            get {
                return ResourceManager.GetString("param_helpsample_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intensity ähnelt.
        /// </summary>
        public static string param_intensity {
            get {
                return ResourceManager.GetString("param_intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effect intensity ähnelt.
        /// </summary>
        public static string param_intensity_tooltip {
            get {
                return ResourceManager.GetString("param_intensity_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iterations ähnelt.
        /// </summary>
        public static string param_iterations {
            get {
                return ResourceManager.GetString("param_iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of iterations and result images ähnelt.
        /// </summary>
        public static string param_iterations_tooltip {
            get {
                return ResourceManager.GetString("param_iterations_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max side length ähnelt.
        /// </summary>
        public static string param_maxsidelength {
            get {
                return ResourceManager.GetString("param_maxsidelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scaling the image, so the longer side length matches the number. ähnelt.
        /// </summary>
        public static string param_maxsidelength_tooltip {
            get {
                return ResourceManager.GetString("param_maxsidelength_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string param_model {
            get {
                return ResourceManager.GetString("param_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model used for image processing ähnelt.
        /// </summary>
        public static string param_model_tooltip {
            get {
                return ResourceManager.GetString("param_model_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string param_name {
            get {
                return ResourceManager.GetString("param_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octave ähnelt.
        /// </summary>
        public static string param_octave {
            get {
                return ResourceManager.GetString("param_octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deepness of the model ähnelt.
        /// </summary>
        public static string param_octave_tooltip {
            get {
                return ResourceManager.GetString("param_octave_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Picture ähnelt.
        /// </summary>
        public static string param_picture {
            get {
                return ResourceManager.GetString("param_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotation ähnelt.
        /// </summary>
        public static string param_rotate {
            get {
                return ResourceManager.GetString("param_rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate image at every iteration. Positive values mean clockwise rotation ähnelt.
        /// </summary>
        public static string param_rotate_tooltip {
            get {
                return ResourceManager.GetString("param_rotate_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scaling ähnelt.
        /// </summary>
        public static string param_scale {
            get {
                return ResourceManager.GetString("param_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale image at every iteration ähnelt.
        /// </summary>
        public static string param_scale_tooltip {
            get {
                return ResourceManager.GetString("param_scale_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shrink ähnelt.
        /// </summary>
        public static string param_shrink {
            get {
                return ResourceManager.GetString("param_shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shrink image to maximum side length of 300px. Increases proccessing performance. ähnelt.
        /// </summary>
        public static string param_shrink_tooltip {
            get {
                return ResourceManager.GetString("param_shrink_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source picture ähnelt.
        /// </summary>
        public static string param_source_picture {
            get {
                return ResourceManager.GetString("param_source_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thumbnail size ähnelt.
        /// </summary>
        public static string param_thumbnail_size {
            get {
                return ResourceManager.GetString("param_thumbnail_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter additional information ähnelt.
        /// </summary>
        public static string report_additional_information {
            get {
                return ResourceManager.GetString("report_additional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author name ähnelt.
        /// </summary>
        public static string report_author {
            get {
                return ResourceManager.GetString("report_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by ähnelt.
        /// </summary>
        public static string report_by {
            get {
                return ResourceManager.GetString("report_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die date ähnelt.
        /// </summary>
        public static string report_date {
            get {
                return ResourceManager.GetString("report_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter ähnelt.
        /// </summary>
        public static string report_parameter {
            get {
                return ResourceManager.GetString("report_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report ähnelt.
        /// </summary>
        public static string report_report {
            get {
                return ResourceManager.GetString("report_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report name ähnelt.
        /// </summary>
        public static string report_report_name {
            get {
                return ResourceManager.GetString("report_report_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results ähnelt.
        /// </summary>
        public static string report_results {
            get {
                return ResourceManager.GetString("report_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die series ähnelt.
        /// </summary>
        public static string report_series {
            get {
                return ResourceManager.GetString("report_series", resourceCulture);
            }
        }
    }
}
